# Generated by Django 5.2 on 2025-04-25 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lickedy_split', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='position',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='ssn',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='SSN must be in format: XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')]),
        ),
    ]
