# Generated by Django 5.2 on 2025-04-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lickedy_split', '0004_alter_newuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
