# Generated by Django 5.2 on 2025-04-27 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lickedy_split', '0005_rename_user_name_newuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(help_text='Enter 10 digits (e.g., 2485551234)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain 9-15 digits only', regex='^\\d{9,15}$')]),
        ),
    ]
