# Generated by Django 5.2 on 2025-04-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lickedy_split', '0006_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes_using', through='lickedy_split.RecipeIngredient', to='lickedy_split.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='lickedy_split.ingredient'),
        ),
    ]
